"use client"

import { useEffect, useState } from "react"
import { ArrowDownRight, ArrowUpRight, Github, Menu, Star, X } from "lucide-react"

type Repository = { id: number; name: string; html_url: string; description: string | null; language: string | null; stargazers_count: number; fork: boolean }
const github = "https://github.com/adarshpadhan"
const featured = [
  { number: "01", title: "Virtual Private Cloud", text: "A secure AWS compute environment designed around a practical cloud networking architecture.", tags: ["AWS", "Networking"] },
  { number: "02", title: "Portfolio", text: "A living space for experiments, shipped work and the things I am learning along the way.", tags: ["Next.js", "Design"] },
]

export default function Home() {
  const [repos, setRepos] = useState<Repository[]>([])
  const [reposLoaded, setReposLoaded] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  useEffect(() => { fetch("https://api.github.com/users/adarshpadhan/repos?sort=updated&per_page=100").then((r) => r.ok ? r.json() : []).then((data: Repository[]) => setRepos(data.filter((repo) => !repo.fork).slice(0, 6))).catch(() => setRepos([])).finally(() => setReposLoaded(true)) }, [])
  const closeMenu = () => setMenuOpen(false)
  return <main>
    <header className="site-header"><a href="#top" className="brand" aria-label="Adarsh home">adarsh<span>.</span></a><nav className={menuOpen ? "nav open" : "nav"} aria-label="Primary navigation"><a href="#work" onClick={closeMenu}>work</a><a href="#about" onClick={closeMenu}>about</a><a href={github} target="_blank" rel="noreferrer">github <ArrowUpRight size={13} /></a></nav><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X /> : <Menu />}</button></header>
    <section id="top" className="hero section-grid"><div className="hero-copy reveal"><p className="index">01 <i /> INTRODUCTION</p><h1>Building useful<br />things for the web<span>.</span></h1><p className="lede">Hi, I’m Adarsh Kumar Padhan — a web developer interested in fast, accessible and delightful web experiences.</p><a className="text-link" href="#work">Explore my work <ArrowDownRight /></a></div><div className="orbital-art" aria-hidden="true"><div className="orb"><div /><div /><div /></div><b className="cross cross-one">+</b><b className="cross cross-two">+</b></div><div className="hero-foot"><span>01</span><i /><span>IDEAS / CODE / IMPACT</span></div></section>
    <section id="work" className="work section-grid"><div className="section-intro reveal"><p className="index">02 <i /> SELECTED WORK</p><h2>Work that<br />solves <em>real<br />problems.</em></h2><p>A few projects that reflect how I think, build and ship for the web.</p><a className="text-link" href={github} target="_blank" rel="noreferrer">View all work <ArrowUpRight /></a></div><div className="featured-list">{featured.map((project) => <article className="feature reveal" key={project.number}><div className="feature-art"><small>{project.number}</small><span>{project.title === "Virtual Private Cloud" ? "A secure foundation for the cloud." : "Ideas to web experiences."}</span></div><div className="feature-copy"><h3>{project.title}</h3><p>{project.text}</p><a href={github} target="_blank" rel="noreferrer">View project <ArrowUpRight /></a></div><div className="feature-tags">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></article>)}</div></section>
    <section id="github" className="github-section section-grid"><div className="section-intro reveal"><p className="index">03 <i /> GITHUB</p><h2>Live projects<br />on <em>GitHub.</em></h2><p>Open-source projects, experiments and small ideas — updated directly from my public GitHub profile.</p><a className="text-link" href={github} target="_blank" rel="noreferrer">Visit my GitHub <ArrowUpRight /></a></div><div className="repo-list reveal" aria-live="polite">{repos.length ? repos.map((repo) => <a className="repo" href={repo.html_url} target="_blank" rel="noreferrer" key={repo.id}><div><h3>{repo.name}</h3><p>{repo.description || "An open-source project by Adarsh Kumar Padhan."}</p></div><span className="language">{repo.language || "Code"}</span><span className="stars"><Star size={14} fill="currentColor" /> {repo.stargazers_count}</span><ArrowUpRight className="repo-arrow" /></a>) : <div className="repo-loading"><Github /> {reposLoaded ? "GitHub projects are temporarily unavailable." : "Loading public projects from GitHub…"}</div>}</div></section>
    <section id="about" className="about section-grid"><div className="section-intro reveal"><p className="index">04 <i /> ABOUT</p><h2>A little bit<br /><em>about me.</em></h2><p>I’m Adarsh Kumar Padhan, a web developer who enjoys building clear, thoughtful and user-focused experiences.</p></div><div className="about-copy reveal"><p>I care about clean code, good design and building things that are actually useful. I’m constantly learning, experimenting and looking for better ways to create for the web.</p><p>When I’m not coding, you’ll probably find me reading, exploring new tools or thinking about what to build next.</p></div><div className="skills reveal"><h3>Skills</h3>{["HTML", "CSS", "JavaScript", "React", "Next.js", "AWS", "Git"].map((skill) => <span key={skill}>{skill}</span>)}</div></section>
    <footer className="footer"><a className="brand" href="#top">adarsh<span>.</span></a><p>Adarsh Kumar Padhan<br />Web Developer</p><div><small>LET’S BUILD SOMETHING USEFUL.</small><a href="mailto:apadhan@outlook.in">apadhan@outlook.in</a></div><nav><a href="#work">work</a><a href="#about">about</a><a href={github}>github</a></nav><p className="copyright">© {new Date().getFullYear()} Adarsh Kumar Padhan. All rights reserved.</p></footer>
  </main>
}
